/**
 * 3D Foot Scan Utility V2
 * 
 * Supports importing and extracting features from foot scans
 * generated by scanners like 3DMakerpro Toucan or Xianku3D B002.
 * 
 * Now includes a functional Binary STL parser and geometric analysis.
 */

export interface FootFeatures {
    lengthMm: number;
    widthMm: number;
    archHeightMm: number;
    instepGirthMm: number;
    heelWidthMm: number;
}

/**
 * Simple Binary STL Parser & Feature Extractor
 */
export const extractFeaturesFromScan = (buffer: ArrayBuffer): FootFeatures => {
    const view = new DataView(buffer);

    // Binary STL has 80 byte header, then 4 byte triangle count
    if (buffer.byteLength < 84) throw new Error('Invalid STL buffer');

    const triangleCount = view.getUint32(80, true);
    let minX = Infinity, minY = Infinity, minZ = Infinity;
    let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;

    const vertices: [number, number, number][] = [];

    // Each triangle is 50 bytes: 12 (normal) + 36 (3*3*Float32) + 2 (attr)
    for (let i = 0; i < triangleCount; i++) {
        const offset = 84 + i * 50 + 12; // Skip normal

        for (let v = 0; v < 3; v++) {
            const vx = view.getFloat32(offset + v * 12, true);
            const vy = view.getFloat32(offset + v * 12 + 4, true);
            const vz = view.getFloat32(offset + v * 12 + 8, true);

            minX = Math.min(minX, vx);
            minY = Math.min(minY, vy);
            minZ = Math.min(minZ, vz);
            maxX = Math.max(maxX, vx);
            maxY = Math.max(maxY, vy);
            maxZ = Math.max(maxZ, vz);

            // Only keep every Nth vertex for analysis to save memory if needed
            if (i % 10 === 0) vertices.push([vx, vy, vz]);
        }
    }

    const length = maxX - minX;
    const width = maxY - minY;

    // Arch height extraction: Find highest Z in the arch region
    // Assuming Y is width, X is length. Arch is usually at 40-60% of length.
    const archMinX = minX + length * 0.4;
    const archMaxX = minX + length * 0.6;
    let archZMax = minZ;

    vertices.forEach(([x, _y, z]) => {
        if (x >= archMinX && x <= archMaxX) {
            archZMax = Math.max(archZMax, z);
        }
    });

    return {
        lengthMm: length,
        widthMm: width,
        archHeightMm: archZMax - minZ,
        instepGirthMm: width * 2.2, // Rough approximation
        heelWidthMm: width * 0.7,   // Rough approximation
    }
}

export interface ShoeSize {
    euSize: number;
    lengthMm: number;
    widthMm: number;
    widthCategory: 'NARROW' | 'REGULAR' | 'WIDE' | 'EXTRA_WIDE';
}

/**
 * Maps foot measurements to nearest standard shoe size (EU 38-48) with width profile
 */
export const mapToStandardSize = (lengthMm: number, widthMm: number): ShoeSize => {
    // 1. Calculate EU Size: EU Size = (3/2) * (Foot Length in cm + 1.5)
    // We use +1.5 for "last" allowance (space for toes)
    const rawSize = (1.5 * (lengthMm / 10 + 1.5));
    const euSize = Math.round(rawSize);

    // 2. Calculate Width Category (Brannock-like scaling)
    // For EU 44, ~105 is regular. Ratio is approx width/length
    const ratio = widthMm / lengthMm;
    let widthCategory: ShoeSize['widthCategory'] = 'REGULAR';

    if (ratio < 0.36) widthCategory = 'NARROW';
    else if (ratio > 0.42) widthCategory = 'EXTRA_WIDE';
    else if (ratio > 0.39) widthCategory = 'WIDE';

    return {
        euSize: Math.max(38, Math.min(48, euSize)),
        lengthMm: Math.round(lengthMm),
        widthMm: Math.round(widthMm),
        widthCategory
    };
}
