name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  caedo-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install dependencies
        working-directory: caedo-api
        run: pip install -r requirements.txt
      - name: Test
        working-directory: caedo-api
        run: python -m pytest --tb=short
